/** Generated by scripts/generate-sw.mjs — bump version in scripts/offline-version.mjs */
export const OFFLINE_SW_VERSION = 42;

export const OFFLINE_STATIC_CACHE = `blunno-static-v${OFFLINE_SW_VERSION}`;
export const OFFLINE_RUNTIME_CACHE = `blunno-runtime-v${OFFLINE_SW_VERSION}`;
