import { readFile, writeFile } from 'node:fs/promises';

import { OFFLINE_SW_VERSION } from './offline-version.mjs';

const version = String(OFFLINE_SW_VERSION);
const template = await readFile('public/sw.template.js', 'utf8');
const sw = template.replaceAll('__OFFLINE_SW_VERSION__', version);

await writeFile('public/sw.js', sw);

const tsContent = `/** Generated by scripts/generate-sw.mjs — bump version in scripts/offline-version.mjs */
export const OFFLINE_SW_VERSION = ${OFFLINE_SW_VERSION};

export const OFFLINE_STATIC_CACHE = \`blunno-static-v\${OFFLINE_SW_VERSION}\`;
export const OFFLINE_RUNTIME_CACHE = \`blunno-runtime-v\${OFFLINE_SW_VERSION}\`;
`;

await writeFile('src/lib/offlineSwVersion.ts', tsContent);
console.log(`service worker: v${OFFLINE_SW_VERSION} → public/sw.js, src/lib/offlineSwVersion.ts`);
